# Generated by Django 2.0 on 2020-06-19 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImanagerGallery',
            fields=[
                ('gallery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='photologue.Gallery')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('shared_with', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Shared Users')),
            ],
            options={
                'verbose_name': 'Imanager Gallery',
                'verbose_name_plural': 'Imanager Galleries',
                'db_table': 'core_gallery',
            },
            bases=('photologue.gallery',),
        ),
    ]
